# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 04:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import river.models.fields.state


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprofiles', '0001_initial'),
        ('river', '0008_auto_20161017_0916'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name=b'Subject')),
                ('description', models.TextField(blank=True, max_length=1000, verbose_name=b'Description')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taks_by_agent', to='userprofiles.UserProfile')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tasks.Task')),
                ('status', river.models.fields.state.StateField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='river.State', verbose_name=b'Status')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_by_supervisor', to='userprofiles.UserProfile')),
            ],
        ),
    ]
